version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "binance-lambda-sqs"
s3_bucket = "aws-sam-cli-binance-app-sqs-lambda"
s3_prefix = "binance-lambda-sqs"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
